---
output:
  pdf_document: default
---
# Novo Resumo - Inglês
Compressive strength is the main characteristic of concrete. The correct prediction of this parameter means cost and time reduction. This work built predictive models for 6 different ages of concrete samples (3, 7, 14, 28, 56, and 100 days). A set of data obtained in previous studies was used, a total of 1030 samples, with 9 variables: resistance to compression, age, and 7 ingredients (water, cement, fine aggregate, coarse aggregate, fly ash, blast furnace slag, and superplasticizers). Another 6 variables were added to represent the proportions of the main ingredients in each sample (water/cement, fine aggregate/cement, coarse aggregate/cement, fine aggregate/coarse aggregate, water/coarse aggregate, and water/fine aggregate). The predictive models were developed in *R* language, using the *caret* package with the *Parallel Random Forest* algorithm and repeated cross-validation technique to optimize the parameters. The results were satisfactory and compatible with other studies using the same data set. The most important model, 28 days old, obtained *RMSE* of 4.717. The 3-day model obtained the best result, *RMSE* of 3.310. The worst result was the 56-day model, with *RMSE* of 5.939. The work showed that the compressive strength of concrete can be predicted. The choice of creating a model for each age, instead of using age as a predictor, allowed to get compatible results with the available data at each age. It was a promising alternative since good results were achieved by training with just one algorithm. This work facilitates exploration and new efforts to predict the compressive strength of concrete, it can be replicated using different algorithms or the combination of several.

Compressive strength is the main characteristic of concrete. The correct prediction of this parameter results in cost and time reduction. This work built predictive models for 6 different ages of concrete samples (3, 7, 14, 28, 56, and 100 days). Was used a dataset with 9 variables: compressive strength, age, and 7 ingredients (water, cement, fine aggregate, coarse aggregate, fly ash, blast furnace slag, and superplasticizers). Another 6 variables were added to represent the proportions of the main ingredients in each sample (water/cement, fine aggregate/cement, coarse aggregate/cement, fine aggregate/coarse aggregate, water/coarse aggregate, and water/fine aggregate). The predictive models were developed in R language, using the caret package with the Parallel Random Forest algorithm and repeated cross-validation technique to optimize the parameters. The results were satisfactory and compatible with other studies using the same data set. The most important model, 28 days old, obtained RMSE of 4.717. The 3-day model obtained the best result, RMSE of 3.310. The worst result was the 56-day model, with RMSE of 5.939. The work showed that the compressive strength of concrete can be predicted. The choice of creating a model for each age, instead of using age as a predictor, allowed to get compatible results with the available data at each age. It was a promising alternative since good results were achieved by training with just one algorithm. This work facilitates exploration and new efforts to predict the compressive strength of concrete, it can be replicated using different algorithms or the combination of several.

# Novo Resumo - Português
A resistência à compressão é a principal característica do concreto. A previsão correta desse parâmetro significa redução de custo e tempo. Esse trabalho construiu modelos de previsão em 6 idades diferentes de amostras de concreto (3, 7, 14, 28, 56, e 100 dias). Foi utilizado um conjunto de dados obtido em estudos anteriores, um total de 1030 amostras, com 9 variáveis: resistência à compressão, idade e 7 ingredientes (água, cimento, agregado miúdo, agregado graúdo, cinza volante, escória granulada de alto forno e superplastificantes). Outras 6 variáveis foram adicionadas para representar as proporções dos principais ingredientes em cada amostra (água/cimento, agregado miúdo/cimento, agregado graúdo/cimento, agregado miúdo/agregado graúdo, água/agregado graúdo e água/agregado miúdo). Os modelos de previsão foram desenvolvidos em linguagem *R*, utilizando o pacote *caret* com o algoritmo *Parallel Random Forest* e técnica de validação cruzada repetida para otimização dos parâmetros. Os resultados foram satisfatórios e compatíveis com outros estudos utilizando o mesmo conjunto de dados. O modelo mais importante, de 28 dias, obteve *RMSE* de 4,717. O modelo de 3 dias obteve o melhor resultado, *RMSE* de 3,310. O pior resultado foi o modelo de 56 dias, com *RMSE* de 5,939. O trabalho mostrou que a resistência à compressão do concreto pode ser prevista. A escolha de criar um modelo para cada idade, ao invés de utilizar a idade como característica para previsão, permitiu chegar a resultados compatíveis com os dados disponíveis de cada idade. Foi uma alternativa promissora, visto que bons resultados foram atingidos treinando com apenas um algoritmo. Esse trabalho facilita a exploração e novos esforços para previsão da resistência à compressão do concreto, ele pode ser replicado utilizando diferentes algoritmos ou a combinação de diversos.

# Resumo antigo
A resistência à compressão é a principal característica do concreto. Esse trabalho utilizou um conjunto de amostras amplamente utilizado para construir 6 modelos de previsão dessa característica, cada um específicamente para uma idade, 3, 7, 14, 28, 56 e 100 dias a partir de 7 ingredientes (água, cimento, agregado miúdo, agregado graúdo, cinza volante, escória granulada de alto forno e superplastificantes) e 6 relações entre os principais ingredientes (água/cimento, agregado miúdo/cimento, agregado graúdo/cimento, agregado miúdo/agregado graúdo, água/agregado graúdo e água/agregado miúdo) para fazer a previsão. Foi utilizado o algoritmo *Parallel Random Forest* (*parRF* do pacote *caret* de linguagem *R*). Os resultados foram satisfatórios sendo o melhor para o modelo de 3 dias (*RMSE* de 3,31) e pior para o modelo de 100 dias (*RMSE* de 5,85). O modelo de 28 dias apresentou *RMSE* de 4,72. O trabalho indicou que a separação em um modelo para cada idade é promissora e foi capaz de gerar resultados compatíveis ou melhores que outros estudos, abrindo espaço para construção de novos modelos seguindo essa proposta, mas utilizando algoritmos diferentes ou a combinação de diversos algoritmos.
</PT>


# Resumo explodido (o Novo, mesma coisa, não precisa ler, é apenas pra eu me organizar)

## Introdução
A resistência à compressão é a principal característica do concreto. A previsão correta desse parâmetro significa redução de custo e tempo. 

## Objetivo
Esse trabalho construiu modelos de previsão em 6 idades diferentes de amostras de concreto (3, 7, 14, 28, 56, e 100 dias).

## Métodos
Foi utilizado um conjunto de amostras obtido em estudos anteriores, um total de 1030 amostras, com 9 variáveis: resistência à compressão, idade e 7 ingredientes (água, cimento, agregado miúdo, agregado graúdo, cinza volante, escória granulada de alto forno e superplastificantes). Outras 6 variáveis foram adicionadas para representar as proporções dos principais ingredientes em cada amostra (água/cimento, agregado miúdo/cimento, agregado graúdo/cimento, agregado miúdo/agregado graúdo, água/agregado graúdo e água/agregado miúdo). Os modelos de previsão foram desenvolvidos em linguagem *R*, utilizando o pacote *caret* com o algoritmo *Parallel Random Forest* e técnica de validação cruzada repetida para otimização dos parâmetros.

## Resultados
Os resultados foram satisfatórios e compatíveis com outros estudos utilizando o mesmo conjunto de dados. O modelo mais importante, de 28 dias, obteve *RMSE* de 4,717. O modelo de 3 dias obteve o melhor resultado, *RMSE* de 3,310. O pior resultado foi o modelo de 56 dias, com *RMSE* de 5,939.

## Discussão
O trabalho mostrou que a resistência à compressão do concreto pode ser prevista. A escolha de criar um modelo para cada idade, ao invés de utilizar a idade como característica para previsão, permitiu chegar a resultados compatíveis com os dados disponíveis de cada idade. Foi uma alternativa promissora, visto que bons resultados foram atingidos treinando com apenas um algoritmo. Esse trabalho facilita a exploração e novos esforços para previsão da resistência à compressão do concreto, ele pode ser replicado utilizando diferentes algoritmos ou a combinação de diversos.
